### PR TITLE
Fix wrong link

### PR DESCRIPTION
**Pull request by howiezhao**
In App Store, [MrMC Touch](https://apps.apple.com/app/mrmc-touch/id1062986407) is iOS version, [MrMC](https://apps.apple.com/app/mrmc/id1059536415) is TV Version.

### CODE REVIEW

**Comment by dkanada** [comment]
Thanks for the fix, but this change would actually be made at the [original](https://github.com/jellyfin/jellyfin-blog) repository.

**Comment by howiezhao** [comment]
@dkanada OK, I think should add a contribution description in the README.

**Comment by dkanada** [comment]
We should really just remove this entire repository and host it with nginx or something, we just haven't had the time.

**Comment by howiezhao** [comment]
@dkanada Okay, I see, if you need help, I’m happy to help

**Pull request closed without merging**
