### PR TITLE
Adds EPG screenshot to website

### PR DESCRIPTION
**Pull request by dinki**
Adds the EPG screenshot to website

### CODE REVIEW

**Comment by dinki** [comment]
Discussed with @anthonylavado and decided best to only add the EPG screen shot.  This PR addresses this issue:

https://github.com/jellyfin/jellyfin.github.io/issues/8

**Comment by dinki** [comment]
@anthonylavado I guess you didn't care for it?

**Comment by anthonylavado** [comment]
@dinki We're totally overhauling the website

**Comment by anthonylavado** [comment]
Might still toss this in the mix though

**Pull request merged**
