### PR TITLE
Made screenshots wrap and adjusted padding

### PR DESCRIPTION
**Pull request by cewert**
Capture

I used flex-wrap to wrap the images on full screen and added some padding on mobile to the screenshot titles since they were pretty close to the border/horizontal rule that separated them.

Does this work?

### CODE REVIEW

**Comment by cewert** [comment]
I use [prettier](https://prettier.io/) and it looks like I reformatted the whole style.css file.

Is there a style guide for this site? I can resubmit without the formatting if necessary.

**Comment by dkanada** [comment]
No style guide yet since the goal is to use the hugo template eventually. This is an annoying style glitch though, so if you want to rebase the commit with just your change we can merge this sooner rather than later.

**Comment by cewert** [comment]
@dkanada all set

**Comment by anthonylavado** [comment]
Thank you @cewert!

**Pull request merged**
